[project]
name = "gsearch"
version = "0.1.0"
description = "Searching for shapes in geometric graphs."
readme = "README.md"
authors = [
    { name = "jwardbond", email = "jessewb.e@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "click>=8.5.0",
    "networkx>=3.6.1",
    "scipy>=1.18.1",
]

[project.scripts]
gsearch = "gsearch:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyterlab>=4.6.3",
    "pytest>=9.1.1",
]
